### ISSUE TITLE
Site TODO List

### ISSUE THREAD

**Issue by captn3m0** [speakforme/frontend#2]
General TODO list for the frontend. In no particular order:

- [ ] Setup tabs on the website
- [ ] Enable vue locale detection
- [ ] Setup multiple routes for the campaigns.
- [ ] Get a sample dataset (for schema) of the MP/CM email list and set that up
- [ ] Maybe add "phone number" as a first-class field
- [ ] "Render" the response template (we have different ones for banks/MPs for now).
- [ ] i18n. Not sure how to tackle this best with jekyll. 
- [ ] Directions for mygov submission (Srikrishna Committee on Data Protection)

**Comment by jace** [comment]
On mobile, a `mailto:` link will accept several kilobytes of payload. Nothing else is needed. However, Google Inbox truncates the payload when it encounters some characters (as I recall, em dashes), so that needs extra testing.

**Comment by captn3m0** [comment]
Need better tweet text

**Comment by captn3m0** [comment]
Tested the mailto on mobile, works nicely. Need to check on why `bcc` didn't work.

**Comment by jace** [comment]
I'm worried that if em dashes broke Inbox, maybe local language text will as well. We _may_ need a backup copy-paste flow for mobile.

**Comment by captn3m0** [comment]
Current flow:

- Mobile
  - Show 3 links for gmail/yahoo/mailto
- Desktop
  - One button for send email
  - copy text on click
    - success: show message to paste body in the mail client and open mail client
    - failure: show instructions to copy, and then open mail client

I'm trying to detect the user-initiated-copy event so I can open the popup as soon as the user copies the text. Right now it is based on a 2 second timeout.

TODO: Open all mailto links in new tab.

**Comment by captn3m0** [comment]
More issues:

- Someone has reported that Yes Bank is appearing out of order.
- We need drafts reverified against the English version, since we’ve been making amendments.
- Show cc emails somewhere for people copy-pasting everything
